package soy.iko.opencode.core

/**
 * FFI interface to the Rust Crux core.
 *
 * When the native library [libopencode.so] is available, [NativeCoreFfi] is used.
 * Otherwise [PureCoreFfi] provides a pure-Kotlin reimplementation for development.
 */
interface CoreFfi {
    fun update(data: ByteArray): ByteArray
    fun resolve(id: UInt, data: ByteArray): ByteArray
    fun view(): ByteArray

    companion object {
        fun create(): CoreFfi {
            return try {
                NativeCoreFfi()
            } catch (e: Throwable) {
                PureCoreFfi()
            }
        }
    }
}

/**
 * JNI bridge to the Rust [libopencode.so] native library.
 * Generated by BoltFFI.
 */
private class NativeCoreFfi : CoreFfi {
    init {
        System.loadLibrary("opencode")
    }

    private external fun nativeNew(): Long
    private external fun nativeUpdate(ptr: Long, data: ByteArray): ByteArray
    private external fun nativeResolve(ptr: Long, id: Int, data: ByteArray): ByteArray
    private external fun nativeView(ptr: Long): ByteArray

    private val ptr: Long = nativeNew()

    override fun update(data: ByteArray): ByteArray = nativeUpdate(ptr, data)
    override fun resolve(id: UInt, data: ByteArray): ByteArray = nativeResolve(ptr, id.toInt(), data)
    override fun view(): ByteArray = nativeView(ptr)
}
