[package]
name = "shared"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[[bin]]
name = "codegen"
required-features = ["codegen"]

[features]
facet_typegen = ["crux_core/facet_typegen"]
codegen = ["facet_typegen", "dep:clap", "dep:anyhow", "crux_core/typegen"]

[dependencies]
facet = "=0.44"
boltffi = "0.27"
crux_core = "0.19"
crux_http = "0.19"
serde = { version = "1", features = ["derive"] }

# Optional codegen deps
anyhow = { version = "1", optional = true }
clap = { version = "4", optional = true, features = ["derive"] }

[dev-dependencies]
crux_core = { version = "0.19", features = ["testing"] }
